### PR TITLE
Event

### PR DESCRIPTION
**Pull request by cmouse**
Adds event based logging and reduces the amount of clutter to user. Also adds new event `fts_xapian_indexing_finished` that can be used for metrics.

To enable debug logging, one can use log_debug=cat:fts_xapian

### CODE REVIEW

**Comment by cmouse** [comment]
Supercedes #25

**Comment by grosjo** [comment]
@cmouse : adding your changes manually, for me to learn a bit

**Comment by grosjo** [comment]
I tried to read https://doc.dovecot.org/admin_manual/event_design/

Not very clear what is the difference with i_xxx and I don get /when/ the line is sent to log (what is the trigger)

**Comment by cmouse** [comment]
the e ones send events. the debug one is special, the others get triggered normally. the most useful thing you get is metrics from the named event.

and you can use log_debug setting to turn on debug logging.

**Comment by grosjo** [comment]
What do you mean by "get triggered normally" ? What is hte trigger ?

What about e_debug ?

**Comment by cmouse** [comment]
i_info and e_info work similarly. the e version uses the event and inherits things. you can also set log level for it. the debug one will log if the event has forced debug on, or if there is `log_debug = cat:fts_xapian` set in config.

**Comment by grosjo** [comment]
@cmouse Are "events" mandatory to be used ?

**Comment by grosjo** [comment]
I closed this , as I believe topic addressed in this PR is already solved

**Pull request closed without merging**
