### PR TITLE
Ci travis attempt

### PR DESCRIPTION
**Pull request by arodier**
- Added Continuous Integration file using Travis (see issue #76)
- We now have a Travis configuration file that works perfectly.
- Also minor updates on the readme file.

### CODE REVIEW

**Comment by arodier** [comment]
Any issue with using Travis for CI ?

**Comment by grosjo** [comment]
Yes, the changes seems related to Ubuntu/Debian only

>

**Comment by arodier** [comment]
Maybe we can do it incrementally, starting with Debian/Ubuntu, and add the other OS if necessary.
However, I proposed this more as an insurance that there is no issue in the C++ code preventing a full build of the binaries.
In my opinion, it is worth adding it, as a first step to an automatic build continnuous integration.
What do you think ?

**Comment by grosjo** [comment]
I am very not confortable with debian stuff. WOrking on archlinux here. How can this translate into Arch ?

**Pull request closed without merging**
